# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160430_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
